on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * * '
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        run: |
          echo "2+2=4 :)"
  google:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        run: script.sh
        shell: bash
